# Generated by Django 3.0.14 on 2021-07-06 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import teczka.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teczka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('shipowner', models.CharField(max_length=20)),
                ('booking', models.CharField(max_length=20)),
                ('case_number', models.CharField(max_length=4)),
                ('year', models.IntegerField(default=teczka.models.current_year)),
                ('cut_off', models.DateTimeField(default=django.utils.timezone.now)),
                ('ETD', models.DateTimeField(default=django.utils.timezone.now)),
                ('loading_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('container_type', models.CharField(choices=[('40dv', '40 standard'), ('40hc', '40 high cube'), ('40rf', '40 reefer'), ('20dv', '20 standard'), ('20rf', '20 reefer')], max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
