# Generated by Django 3.0.14 on 2021-07-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teczka',
            name='COO',
            field=models.CharField(choices=[('submited', 'wprowadzone'), ('checking', 'wysłane do sprawdzenia'), ('amended', 'wprowadzone poprawki'), ('accepted', 'zaakceptowane'), ('sent', 'oryginał wysłany')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teczka',
            name='SI',
            field=models.CharField(choices=[('submited', 'wprowadzone'), ('checking', 'wysłane do sprawdzenia'), ('amended', 'wprowadzone poprawki'), ('accepted', 'zaakceptowane'), ('sent', 'oryginał wysłany')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teczka',
            name='insurance',
            field=models.CharField(choices=[('submited', 'wprowadzone'), ('checking', 'wysłane do sprawdzenia'), ('amended', 'wprowadzone poprawki'), ('accepted', 'zaakceptowane'), ('sent', 'oryginał wysłany')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teczka',
            name='case_number',
            field=models.CharField(max_length=10),
        ),
    ]
