# Generated by Django 3.0.14 on 2021-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0002_auto_20210706_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='teczka',
            name='destination',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teczka',
            name='COO',
            field=models.CharField(choices=[('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='SI',
            field=models.CharField(choices=[('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='insurance',
            field=models.CharField(choices=[('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
    ]
