# Generated by Django 3.0.14 on 2021-07-07 15:23

from django.db import migrations, models
import django.utils.timezone
import teczka.models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0003_auto_20210706_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='teczka',
            name='load_place',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='COO',
            field=models.CharField(blank=True, choices=[('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='ETD',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='SI',
            field=models.CharField(blank=True, choices=[('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='booking',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='case_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='company',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='container_type',
            field=models.CharField(blank=True, choices=[('40dv', '40 standard'), ('40hc', '40 high cube'), ('40rf', '40 reefer'), ('20dv', '20 standard'), ('20rf', '20 reefer')], max_length=4),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='cut_off',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='destination',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='insurance',
            field=models.CharField(blank=True, choices=[('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='loading_data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='shipowner',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='year',
            field=models.IntegerField(blank=True, default=teczka.models.current_year),
        ),
    ]
