# Generated by Django 3.0.14 on 2021-07-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0004_auto_20210707_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teczka',
            name='company',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='shipowner',
            field=models.CharField(blank=True, choices=[('40dv', '40 standard'), ('40hc', '40 high cube'), ('40rf', '40 reefer'), ('20dv', '20 standard'), ('20rf', '20 reefer')], max_length=4),
        ),
    ]
