# Generated by Django 3.0.14 on 2021-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0005_auto_20210707_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teczka',
            name='shipowner',
            field=models.CharField(blank=True, choices=[('maersk', 'Maersk Line'), ('cma', 'CMA'), ('msc', 'MSC'), ('hapag', 'Hapag Lloyd')], max_length=6),
        ),
    ]
