# Generated by Django 3.0.14 on 2021-07-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0006_auto_20210707_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teczka',
            old_name='ETD',
            new_name='etd',
        ),
        migrations.RemoveField(
            model_name='teczka',
            name='COO',
        ),
        migrations.RemoveField(
            model_name='teczka',
            name='SI',
        ),
        migrations.AddField(
            model_name='teczka',
            name='coo',
            field=models.CharField(blank=True, choices=[(None, 'Brak'), ('waiting', 'Do wprowadzenia'), ('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
        migrations.AddField(
            model_name='teczka',
            name='si',
            field=models.CharField(blank=True, choices=[(None, 'Brak'), ('waiting', 'Do wprowadzenia'), ('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='company',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='insurance',
            field=models.CharField(blank=True, choices=[(None, 'Brak'), ('waiting', 'Do wprowadzenia'), ('submited', 'Wprowadzone'), ('checking', 'Wysłane do sprawdzenia'), ('amended', 'Wprowadzone poprawki'), ('accepted', 'Zaakceptowane'), ('sent', 'Oryginał wysłany')], max_length=30),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='static/documents')),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teczka.Teczka')),
            ],
        ),
    ]
