# Generated by Django 3.0.14 on 2021-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0007_auto_20210712_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
