# Generated by Django 3.0.14 on 2021-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0008_auto_20210712_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name_file',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
