# Generated by Django 3.0.14 on 2021-07-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0009_auto_20210712_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='teczka',
            name='case_status',
            field=models.CharField(blank=True, choices=[('active', 'Aktywna'), ('finished', 'Zakończona')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='teczka',
            name='customs',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='teczka',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teczka',
            name='invoice',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='teczka',
            name='vgm',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
