# Generated by Django 3.0.14 on 2021-07-17 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0011_auto_20210715_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teczka',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='customs',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='cut_off',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 2, 23, 37, 106636), null=True),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='etd',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 2, 23, 37, 106636), null=True),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='invoice',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='loading_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 2, 23, 37, 106636), null=True),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='vgm',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='year',
            field=models.IntegerField(blank=True, default=1999),
        ),
    ]
