# Generated by Django 3.0.14 on 2021-07-17 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0016_auto_20210717_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='teczka',
            name='eta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 19, 55, 52, 267630), null=True),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='cut_off',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 19, 55, 52, 267630), null=True),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='etd',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 19, 55, 52, 267630), null=True),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='loading_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 19, 55, 52, 267630), null=True),
        ),
    ]
