# Generated by Django 3.0.14 on 2021-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0021_auto_20210717_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='teczka',
            name='offer_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='case_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
