# Generated by Django 3.2.5 on 2021-07-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0022_auto_20210717_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teczka',
            name='coo',
            field=models.CharField(blank=True, choices=[(None, 'Brak'), ('waiting', 'Do wprow.'), ('submited', 'Wprowadzone'), ('checking', 'Wysł. do spr.'), ('amended', 'Popr. wprow.'), ('accepted', 'Zaakc.'), ('sent', 'Oryg. wysł.')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='insurance',
            field=models.CharField(blank=True, choices=[(None, 'Brak'), ('waiting', 'Do wprow.'), ('submited', 'Wprowadzone'), ('checking', 'Wysł. do spr.'), ('amended', 'Popr. wprow.'), ('accepted', 'Zaakc.'), ('sent', 'Oryg. wysł.')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='si',
            field=models.CharField(blank=True, choices=[(None, 'Brak'), ('waiting', 'Do wprow.'), ('submited', 'Wprowadzone'), ('checking', 'Wysł. do spr.'), ('amended', 'Popr. wprow.'), ('accepted', 'Zaakc.'), ('sent', 'Oryg. wysł.')], max_length=30),
        ),
    ]
