# Generated by Django 3.2.5 on 2021-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0023_auto_20210719_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teczka',
            name='customs',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teczka',
            name='invoice',
            field=models.NullBooleanField(default=False),
        ),
    ]
