# Generated by Django 3.2.5 on 2021-07-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teczka', '0024_auto_20210720_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='teczka',
            name='import_export',
            field=models.CharField(blank=True, choices=[('imp', 'Import'), ('exp', 'Export')], default='exp', max_length=3),
        ),
    ]
